Create plugin chatwork notify
reg-viz/reg-suit pull request #329
Opened 2020-12-16 17:03 UTC by dieuhd

## What does this change?
Allow push notification to Chatwork.com

Config chatwork-nofity:
```ts
{
  chatworkToken:"xxxx-x-xxxxxx";
  roomID:"123456789";
  mrURL:"$CI_MERGE_REQUEST_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID"; // for gitlab
  mention:"[toall]";
  pipelineURL:  "pipelineURL": "$CI_PIPELINE_URL";
}
```
## Screenshots
<img width="829" alt="Screen Shot 2020-12-16 at 11 41 49 PM" src="https://user-images.githubusercontent.com/3165692/102380542-a060bb80-3ffa-11eb-8c05-8fec74cea408.png">

2020-12-17 17:32 UTC, Quramy requested changes
@dieuhd Thanks for the PR !

I've add some comments. I'll merge soon if you fix them 😄

2020-12-17 17:32 UTC, Quramy commented on packages/reg-notify-chatwork-plugin/src/chatwork-notifier-plugin.ts
> +  pipelineURL?: string;
[nits] reg-suit's other plugins use not `URL` but `Url` suffix convention (e.g. `webhookUrl` or `GitHubUrl` ).
Would you rename to `mrUrl` / `pipelineUrl` ?

2020-12-17 17:32 UTC, Quramy commented on packages/reg-notify-chatwork-plugin/src/chatwork-notifier-plugin.ts
> +  createEmoji(params: NotifyParams) {
I like this :)

2020-12-17 17:32 UTC, Quramy commented on packages/reg-notify-chatwork-plugin/src/chatwork-preparer.ts
> +  webhookUrl?: string;
It seems that this property is never used. Please remove it.

2020-12-21 10:38 UTC, dieuhd commented
@Quramy Thanks for your comments.
I had just fixed it. Please review this PR again.

2020-12-22 03:07 UTC, Quramy approved these changes

2020-12-22 03:07 UTC, merged

2020-12-22 03:58 UTC, Quramy commented
Thanks! I’ve published this as v0.10.10